### ISSUE TITLE
 installing geo-spaas-vagrant and error message

### ISSUE THREAD

**Issue by vak000** [nansencenter/django-geo-spaas#5]
What is this error message I face when installing geo-spaas-vagrant:

"Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again."

Thanks

**Comment by akorosov** [comment]
I failed to understand the error message. Any error output visible above should be provided. Please fix the error reporting and try submitting the issue again.

**Comment by vak000** [comment]
Hi again,

I am following your instructions on nansat installation. I copied the whole error section here. 
Thank,

(nansat) tek-ift-m0006:~ vak000$ pip install https://github.com/nansencenter/nansat/archive/master.tar.gz
Collecting https://github.com/nansencenter/nansat/archive/master.tar.gz
/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Exception:
Traceback (most recent call last):
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
/Users/vak000/anaconda3/envs/nansat/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
(nansat) tek-ift-m0006:~ vak000$

**Comment by akorosov** [comment]
The problem is with the SSL connection. SSLError: [Errno 1] _ssl.c:504: error:14090086:SS That happens outside nansat. Sorry we cannot help with that.

Your python is installed in:
/Users/vak000/anaconda3/envs/nansat/lib/python2.7

Try to follow the recipe given on nansat page for installing pyhon:
```
# download the latest version of miniconda
wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh

# make it executable
chmod +x miniconda.sh

# install miniconda virtual environment
./miniconda.sh -b -f -p $HOME/miniconda
```
Maybe that will help?
Even easier would be to use Vagrant and Ansible. Check [here](https://github.com/nansencenter/geo-spaas-vagrant)
