### ISSUE TITLE
Switch to Django 3

### ISSUE THREAD

**Issue by akorosov** [nansencenter/django-geo-spaas#82]
So far Dockerfile has django==2.2. Otherwise two errors are raised by testing:
```
ERROR: test_search_loads (geospaas.viewer.tests.FormAndViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/django/template/defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
bootstrap_tags
cache
i18n
l10n
leaflet_tags
log
static
tz



======================================================================
ERROR: geospaas.catalog.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: geospaas.catalog.tests
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/conda/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/src/geospaas/catalog/tests.py", line 10, in <module>
    from django.utils.six import StringIO
ModuleNotFoundError: No module named 'django.utils.six'

```

But Django is evolving and so should we.

 - [x] Remove django==2.2 in Dockerfile
 - [x] Fix errors that appear in unittests
 - [x] Make sure new code is backward compatible with Django 2.2

**Comment by aanersc** [comment]
@akorosov 
Please check the modifications. 
Easy peasy!!!  :)
